{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eclipsesource.tabris.android",
    "module": "devtools",
    "version": "3.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "aeuznfedrvcz5a3weqye7dlomu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "devtools-3.6.1.aar",
          "url": "devtools-3.6.1.aar",
          "size": 191136,
          "sha512": "b99c534bff6ec75fbf16a920cd212d6d7655f44e457e27b5d760d182476661be84abd9d565dbfd3ad0b403821e6744f1293bd04b9a4f4f10574ee8eaa97afb19",
          "sha256": "5c647cef10767fb832085e38938f6ffd257a21abe5ba9385e22d1e3b2f73eeca",
          "sha1": "f41b39f0cac87aaa8240371d359ef5c518c246b8",
          "md5": "f6ccf57bcfd587832be8144744198465"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.eclipsesource.tabris.android",
          "module": "tabris",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.budiyev.android",
          "module": "code-scanner",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "devtools-3.6.1.aar",
          "url": "devtools-3.6.1.aar",
          "size": 191136,
          "sha512": "b99c534bff6ec75fbf16a920cd212d6d7655f44e457e27b5d760d182476661be84abd9d565dbfd3ad0b403821e6744f1293bd04b9a4f4f10574ee8eaa97afb19",
          "sha256": "5c647cef10767fb832085e38938f6ffd257a21abe5ba9385e22d1e3b2f73eeca",
          "sha1": "f41b39f0cac87aaa8240371d359ef5c518c246b8",
          "md5": "f6ccf57bcfd587832be8144744198465"
        }
      ]
    }
  ]
}
