{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eclipsesource.tabris.android",
    "module": "inspector",
    "version": "3.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "aeuznfedrvcz5a3weqye7dlomu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "inspector-3.6.1.aar",
          "url": "inspector-3.6.1.aar",
          "size": 42147,
          "sha512": "585bb63a6f6c15fe74b03a8adf03509dfeac196a7956e2e99368ec568e59027ee8155c64b98e8de1541b5aeb397119bff2e2e252b1745b0b46bc7ca0966717f5",
          "sha256": "eeb4bcaeb957bbdb10409d032ad346bfb98fcc4fc92c4d3fece486cb11bc04d3",
          "sha1": "55277abd74deae03efe3cb01221edbe43091bf6e",
          "md5": "44d96d96221336288a4ce9c15221f67c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.eclipsesource.tabris.android",
          "module": "tabris",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.koushikdutta.async",
          "module": "androidasync",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "inspector-3.6.1.aar",
          "url": "inspector-3.6.1.aar",
          "size": 42147,
          "sha512": "585bb63a6f6c15fe74b03a8adf03509dfeac196a7956e2e99368ec568e59027ee8155c64b98e8de1541b5aeb397119bff2e2e252b1745b0b46bc7ca0966717f5",
          "sha256": "eeb4bcaeb957bbdb10409d032ad346bfb98fcc4fc92c4d3fece486cb11bc04d3",
          "sha1": "55277abd74deae03efe3cb01221edbe43091bf6e",
          "md5": "44d96d96221336288a4ce9c15221f67c"
        }
      ]
    }
  ]
}
